int controller_cargarIdMaximo( int *idMaximo);
int controller_cargarJugadoresDesdeTexto(char* path , LinkedList* pArrayListJugador);
int controller_listarSelecciones(LinkedList* pArrayListSeleccion);
int controller_listarJugadores(LinkedList* pArrayListJugador,LinkedList* pArrayListSeleccion);
int controller_cargarJugadoresDesdeBinario(char* path , LinkedList* listaJugadoresBinario,LinkedList* pArrayListSeleccion);
int controller_agregarJugador(LinkedList* pArrayListJugador, int* idMax);
int controller_listar(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_editarJugador(LinkedList* pArrayListJugador,LinkedList* pArrayListSeleccion);
int controller_removerJugador(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_editarSeleccion(LinkedList* pArrayListJugador, LinkedList* pArrayListSeleccion);
int controller_guardarJugadoresModoTexto(char* path , LinkedList* pArrayListJugador);
int controller_guardarMaxId(char* path, int maxId);
int controller_guardarJugadoresModoBinario(char* path , LinkedList* pArrayListJugador,LinkedList* pArrayListSeleccion);
int controller_cargarSeleccionesDesdeTexto(char* path , LinkedList* pArrayListSeleccion);
int controller_guardarSeleccionesModoTexto(char* path , LinkedList* pArrayListSeleccion);
int controller_ordenarJugadoresPorNacionalidadAscendente(LinkedList *pArrayListJugador, LinkedList *pArrayListSeleccion);
int controller_ordenarJugadoresPorNombreAscendente(LinkedList *pArrayListJugador, LinkedList *pArrayListSeleccion);
int controller_ordenarJugadoresPorEdadAscendente(LinkedList *pArrayListJugador,LinkedList *pArrayListSeleccion);
int controller_ordenarSeleccionesPorConfederacionAscendente(LinkedList *pArrayListSeleccion);
int controller_ordenarJugadoresPorNacionalidadDescendente(LinkedList *pArrayListJugador, LinkedList *pArrayListSeleccion);
int controller_ordenarJugadoresPorNombreDescendente(LinkedList *pArrayListJugador, LinkedList *pArrayListSeleccion);
int controller_ordenarJugadoresPorEdadDescendente(LinkedList *pArrayListJugador,LinkedList *pArrayListSeleccion);
int controller_ordenarSeleccionesPorConfederacionDescendente(LinkedList *pArrayListSeleccion);
int controller_ordenarJugadoresPorIdAscendente(LinkedList *pArrayListJugador, LinkedList *pArrayListSeleccion);
